### ISSUE TITLE
`py-irt: command not found` even after doing pip install --upgrade py-irt

### ISSUE THREAD

**Issue by pk1130** [nd-ball/py-irt#17]
Hey @EntilZha and @jplalor! Just saw that `eval` has been implemented :) Thanks a lot! I know that @jplalor had already published version 0.2.1 and done the poetry build required for `py-irt` to be used as a command in bash. For some reason, when I try to upgrade the package on pip, it doesn't recognize that there is a new version of the package available. To summarize the issue:

1. What I tried to run: Tried to run `pip install --upgrade py-irt`. Nothing gets upgraded; against all dependencies, I get an output of `Requirement already satisfied in .......`. Uninstalling and reinstalling does not help. To confirm that an issue exists, I tried uninstalling the package and downloading intermediate versions by explicitly running `pip install py-irt==0.2.1` and `pip install py-irt==0.3.0`. Bash output shows `ERROR: Could not find a version that satisfies the requirement py-irt==0.2.1` and `ERROR: Could not find a version that satisfies the requirement py-irt==0.3.0`.
2. What I expected to happen: I expected the py-irt package to be bumped up from the current version on my machine (version 0.1.1) to 0.3.0 (latest release about 40 minutes ago). 
3. What actually happened: No upgrades occurred. Still stuck on py-irt version 0.1.1. 
4. Python version: 3.6.9. pip version:  21.1.3. All installations done inside virtual environment created using `venv`.

Could one of you please look into what the issue might be and why the versions are not actually available using pip? Is it just me or are other people running into this issue as well? Please respond at your earliest convenience! Thanks a ton!

**Comment by jplalor** [comment]
Can you upgrade to python 3.7 or later? The new versions require 3.7 or greater, as python 3.6 support is ending soon. Then you should be able to pip install the latest version.

**Comment by pk1130** [comment]
Yup, works well! Thanks a lot! Been using python 3.6 by default for a long time now 😅
