### ISSUE TITLE
Clarification on 1PL's guide scale value

### ISSUE THREAD

**Issue by sidney-tio** [nd-ball/py-irt#36]
hey, I just wanted to check if there was any particular reason for using `1.0e3` for the scale factor instead of the standard normal params?

https://github.com/nd-ball/py-irt/blob/d2a27dd55a84459782a5514e752ee48d9a63626e/py_irt/models/one_param_logistic.py#L57-L63

**Comment by jplalor** [comment]
Hi, we use the vague prior setup from prior work as it assumes that little is known about the parameter: See https://www.frontiersin.org/articles/10.3389/fpsyg.2016.01422/full#h6 "Standard Vague Prior"

**Comment by sidney-tio** [comment]
thanks for pointing the article to me

**Comment by jplalor** [comment]
No problem!
