### ISSUE TITLE
cli.py train_and_evaluate outputs

### ISSUE THREAD

**Issue by hetryn** [nd-ball/py-irt#50]
Hey guys,

Is there a reason why example_id is being commented out from the output? How would I interpret the result of the 1-PL evaluation? 

https://github.com/nd-ball/py-irt/blob/ddd8783e8085b07b0f5b571587f1e373aafa36c5/py_irt/cli.py#LL232C1-L241C74

**Comment by jplalor** [comment]
As far as I can tell, there's no reason :). I've put it back and updated. Thanks!
