### ISSUE TITLE
ValueError: Options for priors are vage and hierarchical

### ISSUE THREAD

**Issue by hetryn** [nd-ball/py-irt#51]
```
cli.evaluate(
  model_type='1pl',
  parameter_path='train-eval-1pl/best_parameters.json',
  test_pairs_path='test_pairs.jsonlines',
  output_dir='test-1pl')
```

Running the above evaluation code gives the error `ValueError: Options for priors are vague and hierarchical`. 

* 'train-eval-1pl/best_parameters.json' was trained with minitest.jsonlines
* 'test_pairs.jsonlines' consist of the example data as shown:
{"subject_id": "ken", "item_id": "q1"}
{"subject_id": "ken", "item_id": "q2"}
{"subject_id": "burt", "item_id": "q1"}
{"subject_id": "burt", "item_id": "q3"}

**Comment by crobardet** [comment]
I have the same problem.

**Comment by daavidstein** [comment]
same issue with 2pl

**Comment by jplalor** [comment]
This should be fixed now in the latest version. Thanks for your patience!
