### ISSUE TITLE
3pl and 4pl parameter instability 

### ISSUE THREAD

**Issue by Fordulation** [nd-ball/py-irt#53]
Repeated runs of train-and-evaluate produce unstable estimates of item difficulty and discriminability. Lambdas (i.e. the guessing coefficients?) are unreasonably high (i.e. approaching 1).

I ran train-and-evaluate using the '4pl' model 5 times on the same dataset. These data are constituted by ~1700 subjects responding to 20 items. Presumably this is a large enough dataset to expect stable IRT model parameter estimates. 

Correlations between estimates of item difficulty from run to run are as follows: 

`r      Run2  Run3  Run4  Run5`
`Run1   0.10  0.30  0.32 -0.52`
`Run2        -0.26 -0.30  0.00`
`Run3               0.99 -0.54`
`Run4                    -0.58`

Similar issues appeared when running the 3pl. However, the 2pl model appears to be stable, with correlations between run-to-run item difficulty estimates ranging from 0.89 to 0.99.

**Comment by Fordulation** [comment]
Hi John, unfortunately I don't have those data on me currently, but your comment makes sense. I think it is very possible that the parameter instability was user error on my part.

**Comment by jplalor** [comment]
Got it. I'll close this issue, but if you do encounter it again let me know!
