### ISSUE TITLE
Null values in data

### ISSUE THREAD

**Issue by yysung** [nd-ball/py-irt#59]
IRT is known for being able to incorporate null values, given that some respondents do not provide their answers. Does your package allow this in any way (etc., masking or dataset configuration)?

**Comment by jplalor** [comment]
You can run py-irt train with missing values. The subject-item pair just won't be considered during training. 

For example:

![image](https://github.com/nd-ball/py-irt/assets/1954125/ef0463b7-135a-41bf-984f-5eb5c88a81e9)

![image](https://github.com/nd-ball/py-irt/assets/1954125/4a9cbc12-b615-456d-bb1b-f63ac5700099)

**Comment by jplalor** [comment]
Closing this, but if you have more questions please let us know!
