### ISSUE TITLE
Let argument can be pandas DataFrame

### ISSUE THREAD

**Issue by Li-YingWang** [nd-ball/py-irt#64]
Currently the argument has to be a list of dict.
Is it possable to have imput type dataframe of pandas?
Just like mirt package in R.

**Comment by leo-ware** [comment]
I wrote a pull request for this.

[https://github.com/nd-ball/py-irt/pull/65](https://github.com/nd-ball/py-irt/pull/65)

**Comment by jplalor** [comment]
Thanks! I'll take a look

**Comment by jplalor** [comment]
Just merged GH-65 to address this.
