### ISSUE TITLE
Some Requests

### ISSUE THREAD

**Issue by cjh0526** [nd-ball/py-irt#70]
Could tell me if the 1PL model uses the EM algorithm for parameter estimation. Also, is it possible to estimate parameters with my observational data if it is transformed into non-binary data? Thank you very much for your help.

**Comment by jplalor** [comment]
The 1PL model use variational inference. There is also a fit_MCMC option.

At the moment, the package only supports binarized data. To implement a model that can take continuous values, you would need to make a new file here: https://github.com/nd-ball/py-irt/tree/master/py_irt/models
