### ISSUE TITLE
One Question in example_rps.py

### ISSUE THREAD

**Issue by Djokovic0311** [nd-ball/py-irt#8]
Could you please explain what 'response' means in this example? We are planning to apply this model to a QA mission. Is 'response' the correctness whether the model succeeds in identifying the item or whether the IRT model succeeds in telling the matching relationship last mentioned? 

Also, it couldn't be better if there is some related documentations here.

Thanks a lot and look forward to your reply!

**Comment by jplalor** [comment]
Response refers to whether model A answered item X correctly. So for QA if the answer is correct, response is 1. If it's incorrect, response is 0. 

Documentation updates are coming. Stay tuned!
